### ISSUE TITLE
Implement new fit_mr_ash input "fit0"

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/mr.ash#7]
The idea here is to simplify the model fitting interface by providing a single input "fit0" that contains everything necessary to initialize the model fitting (sa2, beta.init, pi, sigma2). This should be an object of class "mr.ash", and so should also contain all the basic data structures (this will be handled internally by calling init_mr_ash).

With this new input, we will no longer need the other inputs sa2, beta.init, pi and sigma2.

Once this is implemented, the idea is that it is easy to refit a model by calling fit_mr_ash a second time on the output.

For inspiration, see function `fit_poisson_nmf` in the [fastTopics package](https://github.com/stephenslab/fastTopics).

**Comment by pcarbo** [comment]
@eweine Once `init_mr_ash` is fully implemented, the idea is that the default value of `fit0` can be `fit0 = init_mr_ash(X,y)`.

**Comment by eweine** [comment]
See https://github.com/stephenslab/mr.ash/pull/14
