### ISSUE TITLE
Implement new function init_mr_ash

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/mr.ash#8]
This is probably best implemented at the same time as Issue #7. 

See function `init_poisson_nmf` in [fastTopics](https://github.com/stephenslab/fastTopics) for ideas.

**Comment by pcarbo** [comment]
@eweine I reviewed what you have so far. The idea here is that `init_mr_ash` should assign values to all the model parameters, and prepare all the essential data structures. So the function should assign valid values to all the model parameters (sa2, sigma2, pi, etc). 

Some additional improvements/changes:

+ Add X, y as inputs (and do argument checking).

+ Rename beta.init as b.

+ Note sa2 can have any length (even a length of 1, I think?).

+ Use the `ashr` code to initialize sa2 by default. (See function `autoselect.mixsd` in the `ashr` package.) The current default initialization does not adapt well to the data.

+ Initialize the "progress" data frame (it should have zero rows).

+ Note the pi's should be non-negative, and should sum to 1, so please check this. And if they don't sum to 1, normalize them to sum to 1.

+ Give a warning if one or more pi's are zero. The idea is that if a mixture weight starts off at zero, it will always be zero, which means that the corresponding mixture component will never be used. In some cases this is desirable but we should warn about that because in most cases it is not.

+ Please give a few examples to illustrate the different ways the model can be initialized (with and without default settings).

+ Also, as we discussed, implement an option `init.method = c("glmnet", "null")` that provides two different ways of initializing the b's.

**Comment by pcarbo** [comment]
I see now you aren't requiring sa2 to be of length 20. I misunderstood your code. Honestly, I don't think it makes sense to provide pi if sa2 is not provided, so an error should be thrown if that's the case.

**Comment by eweine** [comment]
I just merged a PR to dev that should fix all of these issues. There are a few things outstanding that likely need your review:

(1) I gave initializing sa2 a shot with something like what's being user in ashr, but I'm not sure it's sufficient for our purposes.
(2) Some additional tests are now failing due to small tolerances. I don't think these constitute real issues but I'm not 100% sure.
(3) I attempted to link to the documentation for cv.glment in init_mr_ash but when I test this locally I keep seeing "Internal Server Error" in my RStudio. I'm not sure if this is just a problem on my end or if I did something wrong.

**Comment by pcarbo** [comment]
> I attempted to link to the documentation for cv.glment in init_mr_ash but when I test this locally I keep seeing "Internal Server Error" in my RStudio. I'm not sure if this is just a problem on my end or if I did something wrong.

@eweine Is this error still occurring with the latest commit in the `dev` branch? If so, I will investigate.

**Comment by eweine** [comment]
> > I attempted to link to the documentation for cv.glment in init_mr_ash but when I test this locally I keep seeing "Internal Server Error" in my RStudio. I'm not sure if this is just a problem on my end or if I did something wrong.
> 
> @eweine Is this error still occurring with the latest commit in the `dev` branch? If so, I will investigate.

No, it's resolved!
